<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Backend\Block\Template $block */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>

<?php $scriptString = <<<script
require([
    'jquery',
    'mage/adminhtml/grid'
], function($){
    if (window['export_filter_gridJsObject'] != undefined) {
        export_filter_gridJsObject.resetFilter = function () {
            return varienGrid.prototype.resetFilter.call(this, varienExport.modifyFilterGrid);
        };
        export_filter_gridJsObject.doFilter = function () {
            return varienGrid.prototype.doFilter.call(this, varienExport.modifyFilterGrid);
        };
    }

    $('.data-grid-filters .col-id').html('<label class = "data-grid-checkbox-cell-inner" for = "selectAll"> <input type = "checkbox" name = "select_all" value = "all" id = "selectAll" class = "checkbox admin__control-checkbox"> <label for = "selectAll" > </label></label>');
    $('#selectAll').click(function(e) {
        $(this).closest('table').find('td input:checkbox').prop('checked', this.checked);
    });
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>